name: CI Build & Push

on: # 触发工作流的条件
  push:
    branches:
      - mian
  pull_request:

permissions:
  contents: read  # 允许读取代码仓库内容
  id-token: write # 允许生成OIDC令牌

jobs:
  build:
    runs-on: ubantu-latest
    env:
      REGISTRY: ghcr.io # 注册表服务地址，ghcr.io为GitHub提供的容器注册表
      IMAGE_NAME: bili/auth_service
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry # 登录到注册表
        uses: docker/login-action@v2
        with:
          registry: ${{env.REGISTRY}}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./auth_service
          file: ./auth_service/Dockerfile
          push: true # 为true时表示构建后推送到注册表
          tags: ${{env.REGISTRY}}/bili/auth_service:${{github.sha}}
          build-args: |
            GOPROXY=https://proxy.golang.org

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: ${{env.REGISTRY}}/bili/auth_service:${{github.sha}}
      
      - name: Sign image with cosign (keyless)
        env:
          COSING_EXPERIMENTAL: "1"
        run: |
          curl -LO https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          ./cosign-linux-amd64 sign --keyless ${{env.REGISTRY}}/bili/auth_service:${{github.sha}}